# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afee0d3a741eb08f48ec0d1722afbc1b5398084ca1e2eebc3f22a4762261ba61b5903efa9dc40f095d47628866c76bd5bbac1acc924db05bab5a2572625194af

test:
  secret_key_base: b786b74fd7be8feaa2815e57740ca01eca8318a33273cef96eb5be24982c56a28c798efee610f4a9fcc365e805a956fa25b7a89f118f7c12fd32d3574e319911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
